
package System;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AsianGameServerService", targetNamespace = "http://Servers/", wsdlLocation = "http://localhost:9003/Asian?wsdl")
public class AsianGameServerService
    extends Service
{

    private final static URL ASIANGAMESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASIANGAMESERVERSERVICE_EXCEPTION;
    private final static QName ASIANGAMESERVERSERVICE_QNAME = new QName("http://Servers/", "AsianGameServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9003/Asian?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASIANGAMESERVERSERVICE_WSDL_LOCATION = url;
        ASIANGAMESERVERSERVICE_EXCEPTION = e;
    }

    public AsianGameServerService() {
        super(__getWsdlLocation(), ASIANGAMESERVERSERVICE_QNAME);
    }

    public AsianGameServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASIANGAMESERVERSERVICE_QNAME, features);
    }

    public AsianGameServerService(URL wsdlLocation) {
        super(wsdlLocation, ASIANGAMESERVERSERVICE_QNAME);
    }

    public AsianGameServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASIANGAMESERVERSERVICE_QNAME, features);
    }

    public AsianGameServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsianGameServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "AsianGameServerPort")
    public Server getAsianGameServerPort() {
        return super.getPort(new QName("http://Servers/", "AsianGameServerPort"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "AsianGameServerPort")
    public Server getAsianGameServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servers/", "AsianGameServerPort"), Server.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASIANGAMESERVERSERVICE_EXCEPTION!= null) {
            throw ASIANGAMESERVERSERVICE_EXCEPTION;
        }
        return ASIANGAMESERVERSERVICE_WSDL_LOCATION;
    }

}
