
package System;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EuropeanGameServerService", targetNamespace = "http://Servers/", wsdlLocation = "http://localhost:9002/European?wsdl")
public class EuropeanGameServerService
    extends Service
{

    private final static URL EUROPEANGAMESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EUROPEANGAMESERVERSERVICE_EXCEPTION;
    private final static QName EUROPEANGAMESERVERSERVICE_QNAME = new QName("http://Servers/", "EuropeanGameServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9002/European?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EUROPEANGAMESERVERSERVICE_WSDL_LOCATION = url;
        EUROPEANGAMESERVERSERVICE_EXCEPTION = e;
    }

    public EuropeanGameServerService() {
        super(__getWsdlLocation(), EUROPEANGAMESERVERSERVICE_QNAME);
    }

    public EuropeanGameServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EUROPEANGAMESERVERSERVICE_QNAME, features);
    }

    public EuropeanGameServerService(URL wsdlLocation) {
        super(wsdlLocation, EUROPEANGAMESERVERSERVICE_QNAME);
    }

    public EuropeanGameServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EUROPEANGAMESERVERSERVICE_QNAME, features);
    }

    public EuropeanGameServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EuropeanGameServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "EuropeanGameServerPort")
    public Server getEuropeanGameServerPort() {
        return super.getPort(new QName("http://Servers/", "EuropeanGameServerPort"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "EuropeanGameServerPort")
    public Server getEuropeanGameServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servers/", "EuropeanGameServerPort"), Server.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EUROPEANGAMESERVERSERVICE_EXCEPTION!= null) {
            throw EUROPEANGAMESERVERSERVICE_EXCEPTION;
        }
        return EUROPEANGAMESERVERSERVICE_WSDL_LOCATION;
    }

}
