
package System;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NorthAmericanGameServerService", targetNamespace = "http://Servers/", wsdlLocation = "http://localhost:9004/NorthAmerican?wsdl")
public class NorthAmericanGameServerService
    extends Service
{

    private final static URL NORTHAMERICANGAMESERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException NORTHAMERICANGAMESERVERSERVICE_EXCEPTION;
    private final static QName NORTHAMERICANGAMESERVERSERVICE_QNAME = new QName("http://Servers/", "NorthAmericanGameServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9004/NorthAmerican?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NORTHAMERICANGAMESERVERSERVICE_WSDL_LOCATION = url;
        NORTHAMERICANGAMESERVERSERVICE_EXCEPTION = e;
    }

    public NorthAmericanGameServerService() {
        super(__getWsdlLocation(), NORTHAMERICANGAMESERVERSERVICE_QNAME);
    }

    public NorthAmericanGameServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NORTHAMERICANGAMESERVERSERVICE_QNAME, features);
    }

    public NorthAmericanGameServerService(URL wsdlLocation) {
        super(wsdlLocation, NORTHAMERICANGAMESERVERSERVICE_QNAME);
    }

    public NorthAmericanGameServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NORTHAMERICANGAMESERVERSERVICE_QNAME, features);
    }

    public NorthAmericanGameServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NorthAmericanGameServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "NorthAmericanGameServerPort")
    public Server getNorthAmericanGameServerPort() {
        return super.getPort(new QName("http://Servers/", "NorthAmericanGameServerPort"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "NorthAmericanGameServerPort")
    public Server getNorthAmericanGameServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servers/", "NorthAmericanGameServerPort"), Server.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NORTHAMERICANGAMESERVERSERVICE_EXCEPTION!= null) {
            throw NORTHAMERICANGAMESERVERSERVICE_EXCEPTION;
        }
        return NORTHAMERICANGAMESERVERSERVICE_WSDL_LOCATION;
    }

}
